Add new member
Chestnut-lol/Bookish pull request #2
Opened 2022-07-13 16:27 UTC by Chestnut-lol

Added the following functionalities:
1. Can create new Member by inputting name and email.
2. Enable editting member info.

2022-07-14 08:50 UTC, emilypatsko requested changes

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +    public IActionResult MemberChange(Member inputMember)
You need a line break between lines 53 and 54

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +    public IActionResult MemberQuery(Member member)
For clarity, I would put annotations on each method to indicate if they're GET or POST requests (or something else). You can do this by putting e.g. `[HttpGet]` above the name of the method

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +        // var member = _dbContext.Members.Find(memberId);
Delete commented out code

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Models/Member.cs
>      public virtual List<BookCopy> Books { get; set; }
Why is this virtual?

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +            .Include("Books.Book")
```suggestion
            .Include(m => m.Books)
            .ThenInclude(b => b.Book)
```

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
>      private bool VerifyMemberId(string memberId)
Line break between lines 66 and 67

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
>      private bool VerifyMemberId(string memberId)
I don't see this method being used anywhere?

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +        return View("ErrorMsg", new ErrorMsgModel($"Member added. Your member ID is {memberId}."));
If a member is successfully added, why are we returning an error message? I also think this method needs renaming to be clearer, e.g. `AddNewMember`

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +        string memberId = (int.Parse(_dbContext.Members
I think this might break the first time you ever add a member, as there won't be a 'last' member to find the add of and add 1 to.

For future reference, when you build your database code-first, if you give a model an `Id` property, entity framework picks up that it's the primary key and will automatically generate it for you. Read more here: https://docs.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations#configuring-a-primary-key

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Views/Member/AddMember.cshtml
> +                @Html.TextBoxFor(m => m.Name, new { @class="text",type="name",required="required" })
```suggestion
@Html.TextBoxFor(m => m.Name, new { @class="text", type="name", required="required" })
```

need some more spaces

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Views/Member/EditMember.cshtml
> +            <div style="display:inline">
Try not to use inline styles (eg `style="display:inline"`) and instead make use of the classes that Bootstrap has to offer. The documentation is [here](https://getbootstrap.com/docs/5.1/getting-started/introduction/)

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Views/Member/MemberQuery.cshtml
> +<p></p>
Why are there empty paragraphs?

2022-07-14 08:50 UTC, emilypatsko commented on Bookish/Views/Member/MemberQuery.cshtml
>              if (Model.Books.Count >= 1)
You don't really need an `if` statement with the `foreach` loop - it will loop over all of the items in `Model.Books`, so if there aren't any, the things in the loop just won't execute.

2022-07-14 08:58 UTC, Chestnut-lol commented on Bookish/Models/Member.cs
>      public virtual List<BookCopy> Books { get; set; }
This was suggested by Ben since otherwise the databases don't seem to link to each other

2022-07-14 09:00 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
>      private bool VerifyMemberId(string memberId)
No... but we might use it later...?

2022-07-14 09:01 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +        return View("ErrorMsg", new ErrorMsgModel($"Member added. Your member ID is {memberId}."));
Sorry the naming was really bad - the error message class should have been named a "message" class. It is just a page of plain text with a provided message.

2022-07-14 09:04 UTC, BenRamchandani commented on Bookish/Models/Member.cs
>      public virtual List<BookCopy> Books { get; set; }
I may well be wrong about this to be honest - it's required for lazy loading, but it looks like that's disabled by default in EF Core. Worth trying to remove it and seeing what happens.

2022-07-14 10:26 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +        string memberId = (int.Parse(_dbContext.Members
Yes I have changed the way member Id is generated - it is now the time stamp for the time of creation.

2022-07-14 10:26 UTC, Chestnut-lol commented on Bookish/Models/Member.cs
>      public virtual List<BookCopy> Books { get; set; }
Ok, we will try it out after we merge together in case of nasty conflicts?

2022-07-14 15:01 UTC, emilypatsko requested changes

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Bookish.csproj
> +    </ItemGroup>
I think these lines got added by accident... you should be able to delete them. Check the project still runs properly when you do!

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +    public IActionResult MemberQuery(Member member)
@Chestnut-lol Not sure if you didn't see this comment - could you add these annotations to each controller method? Let me know if you'd like to talk more about what they mean :)

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +    public IActionResult MemberQuery(Member member)
I would rename this method to be more descriptive - what does the method do?

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +            return SearchMemberById(member.MemberId);
I think these should really be `return RedirectToActionResult`s

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +    private IActionResult SearchMemberById(string memberId)
Nice clear method name 😃 

This method is structured well! You should adopt this structure in the rest of your methods. 

- Sanitise inputs
- Get relevant models from inputs
- Check any conditions are met - if not, early return with an error view, or redirect
- Otherwise (all conditions met), do whatever logic you want
- Return the view

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
>              .ToList()[0];
I think I already commented about this on Blanca's PR:

```suggestion
var resultMember = _dbContext.Members
    .Where(x => x.MemberId == memberId)
    .Include(m => m.Books)
    .ThenInclude(b => b.Book)
    .SingleOrDefault()
```

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +        // var member = _dbContext.Members.Find(memberId);
Is there a reason you're keeping this commented code in?

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +            .ToList()[0];
Similar comment as earlier - you shouldn't need to index the results like this. If you're only expecting one model to be returned,  you can use `SingleOrDefault()`

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
>      private bool VerifyMemberId(string memberId)
Not a reason to add it now - there's a concept in writing good code known as YAGNI (you ain't gonna need it). Take a look [here](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it). Basically, don't add functionality until you need it! 😄

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +    public IActionResult MemberInput(Member member)
I would rename this method e.g. `AddMember`

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Controllers/MemberController.cs
> +        return View("ErrorMsg", new ErrorMsgModel($"Member added. Your member ID is {member.MemberId}."));
It doesn't make sense to me to return a view called ErrorMsg if the action is performed successfully...

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/AddMember.cshtml
>                  <p></p>
Shouldn't have empty paragraphs - you may want to read about using semantic HTML

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/AddMember.cshtml
>          @using (Html.BeginForm("MemberInput", "Member", FormMethod.Get))
If this is a form to add a new member, it's submitting new data, and probably shouldn't be a GET method

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/EditMember.cshtml
> +    @using (Html.BeginForm("MemberChange", "Member", FormMethod.Get))
Similar here - forms are used for submitting data, which is typical of a POST request, not GET - GET requests don't submit any new data

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/EditMember.cshtml
> +                        new { Value = Model.Name })
This doesn't need to be on a new line

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/EditMember.cshtml
> +        @* Below is expired code.
If this code isn't being used any more, delete it rather than commenting it out

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberCatalogue.cshtml
> +    <table style="width:100%">
Inline style usage

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberCatalogue.cshtml
> +            foreach (var member in Model)
Rather than having a `List<Member>` as the model, I would create a new folder called `ViewModels`, and within it create a `MemberCatalogueViewModel`, which would contain all the information you'd want to show on this page. (e.g. it could include a `List<Member>` called `Members`)

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberQuery.cshtml
> +    @*@using (Html.BeginForm("EditMember", "Member", new{Model.MemberId}, FormMethod.Get))
If this code isn't being used, I would delete it

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberQuery.cshtml
>      <table style="width:100%">
Inline style

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberQuery.cshtml
>      <p></p>
Empty paragraph

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberQueryByNameOrEmail.cshtml
> +    <table style="width:100%">
Inline style

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberQueryByNameOrEmail.cshtml
> +            foreach (var member in Model)
Similar comment to earlier - create a ViewModel to hold the information you want to display on a particular view

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberSearch.cshtml
> +                            new { Type="number" })
Doesn't need to be on new line

2022-07-14 15:01 UTC, emilypatsko commented on Bookish/Views/Member/MemberSearch.cshtml
>          @using (Html.BeginForm("MemberQuery", "Member", FormMethod.Get))
Probably should be a POST method

2022-07-14 15:24 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +            .ToList()[0];
No... I tried using that but member.Books got lost somehow along the way, so we had to do it that way... (SingleOrDefault doesn't work either)

2022-07-14 15:32 UTC, Chestnut-lol commented on Bookish/Views/Member/AddMember.cshtml
>                  <p></p>
Yeah ok I've changed them to line breaks.

2022-07-14 15:41 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +        return View("ErrorMsg", new ErrorMsgModel($"Member added. Your member ID is {member.MemberId}."));
Yeah I'm hoping to change it after the merging because this model is called extensively across the whole project...

2022-07-14 16:25 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +    private IActionResult SearchMemberById(string memberId)
Yeah sure will do.

2022-07-14 16:25 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +            .ToList()[0];
Nvm done now :-)

2022-07-14 16:26 UTC, Chestnut-lol commented on Bookish/Views/Member/AddMember.cshtml
>          @using (Html.BeginForm("MemberInput", "Member", FormMethod.Get))
Right, changed it to a POST method.

2022-07-14 16:27 UTC, Chestnut-lol commented on Bookish/Views/Member/EditMember.cshtml
> +    @using (Html.BeginForm("MemberChange", "Member", FormMethod.Get))
Right - sure.

2022-07-14 16:28 UTC, Chestnut-lol commented on Bookish/Views/Member/EditMember.cshtml
> +        @* Below is expired code.
ok

2022-07-14 16:28 UTC, Chestnut-lol commented on Bookish/Views/Member/EditMember.cshtml
> +                        new { Value = Model.Name })
ok

2022-07-15 08:27 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +        // var member = _dbContext.Members.Find(memberId);
no, I've deleted them.

2022-07-15 08:27 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
>      private bool VerifyMemberId(string memberId)
yeah sure. I've deleted them.

2022-07-15 08:27 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +        return View("ErrorMsg", new ErrorMsgModel($"Member added. Your member ID is {memberId}."));
I've changed it to another class MsgModel now, hopefully it will make more sense.

2022-07-15 08:44 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +            return SearchMemberById(member.MemberId);
ok, I have changed the code.

2022-07-15 08:45 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
>              .ToList()[0];
ok, I have changed it.

2022-07-15 09:07 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberCatalogue.cshtml
> +    <table style="width:100%">
ok deleted.

2022-07-15 09:12 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberCatalogue.cshtml
> +            foreach (var member in Model)
ok done.

2022-07-15 09:13 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberQuery.cshtml
> +    @*@using (Html.BeginForm("EditMember", "Member", new{Model.MemberId}, FormMethod.Get))
ok.

2022-07-15 09:13 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberQuery.cshtml
>      <table style="width:100%">
ok, deleted.

2022-07-15 09:14 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberQueryByNameOrEmail.cshtml
> +    <table style="width:100%">
ok. deleted.

2022-07-15 09:20 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberQuery.cshtml
>      <p></p>
ok deleted.

2022-07-15 09:20 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberQueryByNameOrEmail.cshtml
> +            foreach (var member in Model)
ok done.

2022-07-15 09:21 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberSearch.cshtml
> +                            new { Type="number" })
ok done.

2022-07-15 09:22 UTC, Chestnut-lol commented on Bookish/Views/Member/MemberSearch.cshtml
>          @using (Html.BeginForm("MemberQuery", "Member", FormMethod.Get))
yes, changed.

2022-07-15 09:22 UTC, Chestnut-lol commented on Bookish/Controllers/MemberController.cs
> +    public IActionResult MemberQuery(Member member)
I'll rename it after merging with Blanca? Just because this method might have been used by her too.

2022-07-15 14:19 UTC, merged